name: Print

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Show the source branch
        if: github.event_name == 'pull_request'
        run: echo "Source branch is: ${{ github.head_ref }}"
